name: s_play
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_svg: ^2.2.0

flutter:
  uses-material-design: true

  fonts:
  - family: Fasthand
    fonts:
      - asset: assets/fonts/Fasthand-Regular.ttf
  
  - family: Merienda
    fonts:
      - asset: assets/fonts/Merienda-Regular.ttf
      - asset: assets/fonts/Merienda-ExtraBold.ttf

  assets:
  - assets/icons/


  