name: s_play
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  audiotags: ^1.4.5
  flutter_svg: ^2.2.0
  ffi: ^2.1.4
  collection: ^1.19.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: Fasthand
    fonts:
      - asset: assets/fonts/Fasthand-Regular.ttf
  
  - family: Merienda
    fonts:
      - asset: assets/fonts/Merienda-Regular.ttf
      - asset: assets/fonts/Merienda-ExtraBold.ttf

  assets:
  - assets/icons/


  